import 'package:customer/app/flavor.dart';
import 'package:customer/firebase_options.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Initialises Firebase using the real project options generated by FlutterFire.
///
/// In dev flavor, Auth is still routed to the local emulator (port 9099) so
/// you can test without sending real SMS. In staging/prod, real Firebase Auth
/// is used — phone OTP sends a live SMS via the task-app-20c5f project.
///
/// Returns true if Firebase initialised successfully; false on any failure so
/// the app can still boot in a degraded state.
Future<bool> initFirebase(Flavor flavor) async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    if (flavor == Flavor.dev) {
      final String host = kIsWeb ? '127.0.0.1' : 'localhost';
      await FirebaseAuth.instance.useAuthEmulator(host, 9099);
    }

    return true;
  } catch (e, st) {
    debugPrint('Firebase init failed: $e\n$st');
    return false;
  }
}
