import 'package:customer/app/flavor.dart';
import 'package:customer/firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Initialises Firebase using the real project options generated by FlutterFire.
///
/// Every flavor talks to the live task-app-20c5f project: Auth, Firestore and
/// Storage all use the cloud backend, so phone OTP sends a real SMS and posted
/// jobs land in cloud Firestore. To test against the local emulator suite
/// instead, route BOTH Auth and Firestore to it (never just one — an
/// emulator-issued auth token is rejected by cloud Firestore with
/// permission-denied, and vice versa) and make sure `firebase emulators:start`
/// is actually running, or every read/write hangs waiting on a dead port.
///
/// Returns true if Firebase initialised successfully; false on any failure so
/// the app can still boot in a degraded state.
Future<bool> initFirebase(Flavor flavor) async {
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
    return true;
  } catch (e, st) {
    debugPrint('Firebase init failed: $e\n$st');
    return false;
  }
}
