"use client";

import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { performFirestoreOperation, subscribeDashboard } from "@/lib/firebase/repository";
import { assertDemoCanRun } from "@/lib/demo-mode";
import type { AdminUser, AiExecution, AiMemory, AiReport, Banner, Category, Complaint, Customer, DatabaseState, InstapayReview, Job, JobStatus, Notification, Payout, PromoCode, Provider, ProviderDocumentStatus, ProviderLocation, Role, Service, Severity, SupportConversation, Transaction } from "@/lib/types";
import type { StoredDocumentFile } from "@/lib/document-storage";

type CreateCustomer=Pick<Customer,"name"|"email"|"phone">;
type CreateProvider=Pick<Provider,"name"|"email"|"phone"|"trade">&Partial<Pick<Provider,"nationalIdNumber"|"cities"|"areas">>;
type CreateService=Pick<Service,"name"|"categoryId"|"basePrice">&Partial<Service>;
type CreateJob={customerId:string;serviceId:string;area:string;scheduled:string;amount:number;providerId?:string;address?:string;priceOverrideReason?:string;priority?:Job["priority"];gps?:Job["gps"];city?:string;problemDescription?:string;customerBudget?:number;bookingType?:Job["bookingType"];emergencyFee?:number;emergencyResponseSlaMinutes?:number;scheduledAt?:string;appointmentReminderAt?:string;responseSlaMinutes?:number;arrivalSlaMinutes?:number;completionSlaMinutes?:number;quotationStatus?:Job["quotationStatus"];quotedPrice?:number;quotationNotes?:string};
type UploadedDocument=StoredDocumentFile&{storageKey?:string;key?:string;type:string;customLabel?:string;expiryDate?:string;uploadedBy:string;required:boolean};
type ReplacementDocument=StoredDocumentFile&{storageKey?:string;key?:string;expiryDate?:string;uploadedBy:string};

interface AdminActions {
  createAiExecution(input:Partial<AiExecution>):Promise<AiExecution>;updateAiExecution(id:string,patch:Partial<AiExecution>):Promise<unknown>;acceptAiRecommendation(id:string,recommendationId:string):Promise<unknown>;rememberAiContext(input:Partial<AiMemory>):Promise<AiMemory>;createAiReport(input:Partial<AiReport>):Promise<AiReport>;
  createCustomer(input:CreateCustomer):Promise<Customer>;updateCustomer(id:string,patch:Partial<Customer>):Promise<unknown>;deleteCustomer(id:string):Promise<unknown>;toggleCustomer(id:string):Promise<unknown>;suspendCustomer(id:string):Promise<unknown>;adjustWallet(id:string,amount:number,note:string):Promise<unknown>;
  createProvider(input:CreateProvider):Promise<Provider>;updateProvider(id:string,patch:Partial<Provider>):Promise<unknown>;updateProviderLocation(providerId:string,lat:number,lng:number,status:ProviderLocation["status"],accuracy?:number,heading?:number):Promise<ProviderLocation>;deleteProvider(id:string):Promise<unknown>;toggleProvider(id:string):Promise<unknown>;setProviderDecision(id:string,decision:"approve"|"reject"|"suspend"|"ban"):Promise<unknown>;
  uploadProviderDocument(providerId:string,input:UploadedDocument):Promise<unknown>;replaceProviderDocument(providerId:string,documentId:string,input:ReplacementDocument):Promise<unknown>;reviewProviderDocument(providerId:string,documentId:string,status:ProviderDocumentStatus,notes:string,reviewer:string):Promise<unknown>;deleteProviderDocument(providerId:string,documentId:string):Promise<unknown>;recordProviderDocumentAccess(providerId:string,documentId:string,action:"preview"|"download"):Promise<unknown>;assignVerificationOfficer(providerId:string,adminId:string):Promise<unknown>;addProviderVerificationNote(providerId:string,note:string):Promise<unknown>;updateProviderBackgroundCheck(providerId:string,status:Provider["verification"]["backgroundCheck"]):Promise<unknown>;
  createCategory(input:Pick<Category,"name"|"description">):Promise<Category>;updateCategory(id:string,patch:Partial<Category>):Promise<unknown>;deleteCategory(id:string):Promise<unknown>;createService(input:CreateService):Promise<Service>;updateService(id:string,patch:Partial<Service>):Promise<unknown>;deleteService(id:string):Promise<unknown>;toggleService(id:string):Promise<unknown>;
  createBanner(input:Omit<Banner,"id"|"createdAt"|"updatedAt">):Promise<Banner>;updateBanner(id:string,patch:Partial<Banner>):Promise<unknown>;deleteBanner(id:string):Promise<unknown>;createConversation(input:Pick<SupportConversation,"subject"|"priority">&Partial<SupportConversation>):Promise<SupportConversation>;updateConversation(id:string,patch:Partial<SupportConversation>):Promise<unknown>;addConversationMessage(id:string,text:string):Promise<unknown>;deleteConversation(id:string):Promise<unknown>;
  createJob(input:CreateJob):Promise<Job>;updateJob(id:string,patch:Partial<Job>):Promise<unknown>;assignProvider(jobId:string,providerId:string,override?:boolean):Promise<unknown>;changeJobStatus(id:string,status:JobStatus):Promise<unknown>;refundJob(id:string):Promise<unknown>;addJobNote(id:string,note:string):Promise<unknown>;updateCancellation(id:string,patch:Partial<NonNullable<Job["cancellation"]>>):Promise<unknown>;flagMessage(jobId:string,messageId:string,note:string):Promise<unknown>;reviewCall(jobId:string,callId:string,patch:{reviewed?:boolean;flagged?:boolean;reviewNote?:string;complaintId?:string}):Promise<unknown>;reviewInstapay(id:string,status:InstapayReview["status"],note:string):Promise<unknown>;setWalletFrozen(ownerId:string,frozen:boolean,reason:string):Promise<unknown>;deleteJob(id:string):Promise<unknown>;
  createComplaint(input:Pick<Complaint,"title"|"description"|"severity">&Partial<Complaint>):Promise<Complaint>;updateComplaint(id:string,patch:Partial<Complaint>):Promise<unknown>;setCaseOwner(id:string,adminId:string):Promise<unknown>;setCaseSeverity(id:string,severity:Severity):Promise<unknown>;addCaseNote(id:string,note:string):Promise<unknown>;closeCase(id:string):Promise<unknown>;reopenCase(id:string):Promise<unknown>;deleteComplaint(id:string):Promise<unknown>;
  createPayout(providerId:string,amount:number,method:Payout["method"]):Promise<Payout>;verifyPayout(id:string,reference:string):Promise<unknown>;createTransaction(input:Omit<Transaction,"id"|"createdAt">):Promise<Transaction>;updateTransaction(id:string,patch:Partial<Transaction>):Promise<unknown>;
  createAdmin(input:Pick<AdminUser,"name"|"email"|"role"|"roleId">&{phone?:string;department?:string;isDemoUser?:boolean;demoExpiresAt?:string;demoCompanyName?:string;demoContactName?:string;demoNotes?:string}):Promise<AdminUser>;resendInvitation(id:string):Promise<unknown>;revokeInvitation(id:string):Promise<unknown>;updateAdmin(id:string,patch:Partial<AdminUser>):Promise<unknown>;deleteAdmin(id:string):Promise<unknown>;toggleAdmin(id:string):Promise<unknown>;syncAuthUsers():Promise<unknown>;createRole(input:Pick<Role,"name"|"description"|"permissions">):Promise<Role>;updateRole(id:string,patch:Partial<Pick<Role,"name"|"description"|"permissions">>):Promise<unknown>;deleteRole(id:string):Promise<unknown>;
  createPromo(input:Omit<PromoCode,"id"|"used"|"startsAt">):Promise<PromoCode>;updatePromo(id:string,patch:Partial<PromoCode>):Promise<unknown>;deletePromo(id:string):Promise<unknown>;createNotification(input:Pick<Notification,"title"|"body"|"audience">):Promise<Notification>;reset():Promise<void>;refresh():Promise<void>;
  resetDemoData():Promise<unknown>;
}

interface AdminDataContextValue{db:DatabaseState;actions:AdminActions;loading:boolean;mutationPending:boolean;error:string|null}
const AdminDataContext=createContext<AdminDataContextValue|null>(null);
const emptyDatabase:DatabaseState={aiExecutions:[],aiMemories:[],aiReports:[],customers:[],providers:[],jobs:[],categories:[],services:[],banners:[],conversations:[],verificationRequirements:[],wallets:[],transactions:[],complaints:[],reviews:[],admins:[],invitations:[],roles:[],promos:[],notifications:[],payouts:[],auditLogs:[],locations:[],instapayReviews:[],sequences:{provider:0},issuedProviderIds:[]};

async function responseJson(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok){const error=(data as {error?:unknown}).error;throw new Error(typeof error==="string"?error:"The server could not complete this action")}return data as {result?:unknown}&Record<string,unknown>}

export function AdminDataProvider({children}:{children:React.ReactNode}){
  const{user,loading:authLoading,getIdToken}=useAuth();const[db,setDb]=useState<DatabaseState>(emptyDatabase);const[loading,setLoading]=useState(true);const[mutationCount,setMutationCount]=useState(0);const[error,setError]=useState<string|null>(null);
  const refresh=useCallback(async()=>{},[]);
  useEffect(()=>{if(authLoading)return;if(!user){setDb(emptyDatabase);setError(null);setLoading(false);return}setLoading(true);setError(null);const unsubscribe=subscribeDashboard(user,(state)=>{setDb(state);setLoading(false)},(reason)=>{setError(reason.message);setLoading(false)});return unsubscribe},[authLoading,user]);
  const execute=useCallback(async<T,>(action:string,payload:Record<string,unknown>={}):Promise<T>=>{if(!user)throw new Error("Sign in required");setMutationCount((value)=>value+1);setError(null);try{assertDemoCanRun(user,action);const result=await performFirestoreOperation<T>(action,payload,user);window.dispatchEvent(new CustomEvent("task:operation-success",{detail:{action}}));return result}catch(reason){const message=reason instanceof Error?reason.message:"Firestore operation failed";setError(message);window.dispatchEvent(new CustomEvent("task:operation-error",{detail:{message}}));throw reason}finally{setMutationCount((value)=>Math.max(0,value-1))}},[user]);
  const apiRequest=useCallback(async<T,>(url:string,body:Record<string,unknown>)=>{const action=String(body.action??"serverAction");setMutationCount((value)=>value+1);setError(null);try{if(!user)throw new Error("Sign in required");assertDemoCanRun(user,action);const token=await getIdToken();const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify(body)});const data=await responseJson(response) as T;window.dispatchEvent(new CustomEvent("task:operation-success",{detail:{action}}));return data}catch(reason){const message=reason instanceof Error?reason.message:"Server operation failed";console.error(`[Task Admin] ${action} failed`,reason);setError(message);window.dispatchEvent(new CustomEvent("task:operation-error",{detail:{message}}));throw reason}finally{setMutationCount((value)=>Math.max(0,value-1))}},[getIdToken,user]);
  const adminRequest=useCallback(async<T,>(body:Record<string,unknown>)=>apiRequest<T>("/api/firebase/admin-users",body),[apiRequest]);
  const operationsRequest=useCallback(async<T,>(body:Record<string,unknown>)=>apiRequest<T>("/api/firebase/operations",body),[apiRequest]);
  const demoResetRequest=useCallback(async<T,>()=>apiRequest<T>("/api/firebase/demo/reset",{}),[apiRequest]);
  const actions=useMemo<AdminActions>(()=>({
    createAiExecution:(input)=>execute("createAiExecution",{input}),updateAiExecution:(id,patch)=>execute("updateAiExecution",{id,patch}),acceptAiRecommendation:(id,recommendationId)=>execute("acceptAiRecommendation",{id,recommendationId}),rememberAiContext:(input)=>execute("rememberAiContext",{input}),createAiReport:(input)=>execute("createAiReport",{input}),
    createCustomer:(input)=>execute("createCustomer",{input}),updateCustomer:(id,patch)=>execute("updateCustomer",{id,patch}),deleteCustomer:(id)=>operationsRequest({action:"deleteCustomer",id}),toggleCustomer:(id)=>operationsRequest({action:"toggleCustomer",id}),suspendCustomer:(id)=>operationsRequest({action:"toggleCustomer",id}),adjustWallet:(id,amount,note)=>execute("adjustWallet",{id,amount,note}),
    createProvider:(input)=>execute("createProvider",{input}),updateProvider:(id,patch)=>execute("updateProvider",{id,patch}),updateProviderLocation:(providerId,lat,lng,status,accuracy,heading)=>execute("updateProviderLocation",{providerId,lat,lng,status,accuracy,heading}),deleteProvider:(id)=>operationsRequest({action:"deleteProvider",id}),toggleProvider:(id)=>operationsRequest({action:"toggleProvider",id}),setProviderDecision:(id,decision)=>execute("setProviderDecision",{id,decision}),
    uploadProviderDocument:(providerId,input)=>execute("uploadProviderDocument",{providerId,input}),replaceProviderDocument:(providerId,documentId,input)=>execute("replaceProviderDocument",{providerId,documentId,input}),reviewProviderDocument:(providerId,documentId,status,notes,reviewer)=>execute("reviewProviderDocument",{providerId,documentId,status,notes,reviewer}),deleteProviderDocument:(providerId,documentId)=>execute("deleteProviderDocument",{providerId,documentId}),recordProviderDocumentAccess:(providerId,documentId,accessAction)=>execute("recordProviderDocumentAccess",{providerId,documentId,accessAction}),assignVerificationOfficer:(providerId,adminId)=>execute("assignVerificationOfficer",{providerId,adminId}),addProviderVerificationNote:(providerId,note)=>execute("addProviderVerificationNote",{providerId,note}),updateProviderBackgroundCheck:(providerId,verificationStatus)=>execute("updateProviderBackgroundCheck",{providerId,status:verificationStatus}),
    createCategory:(input)=>execute("createCategory",{input}),updateCategory:(id,patch)=>execute("updateCategory",{id,patch}),deleteCategory:(id)=>execute("deleteCategory",{id}),createService:(input)=>execute("createService",{input}),updateService:(id,patch)=>execute("updateService",{id,patch}),deleteService:(id)=>execute("deleteService",{id}),toggleService:(id)=>execute("toggleService",{id}),
    createBanner:(input)=>execute("createBanner",{input}),updateBanner:(id,patch)=>execute("updateBanner",{id,patch}),deleteBanner:(id)=>execute("deleteBanner",{id}),createConversation:(input)=>execute("createConversation",{input}),updateConversation:(id,patch)=>execute("updateConversation",{id,patch}),addConversationMessage:(id,text)=>execute("addConversationMessage",{id,text}),deleteConversation:(id)=>execute("deleteConversation",{id}),
    createJob:(input)=>execute("createJob",{input}),updateJob:(id,patch)=>execute("updateJob",{id,patch}),assignProvider:(jobId,providerId,override=false)=>execute("assignProvider",{jobId,providerId,override}),changeJobStatus:(id,jobStatus)=>execute("changeJobStatus",{id,status:jobStatus}),refundJob:(id)=>execute("refundJob",{id}),addJobNote:(id,note)=>execute("addJobNote",{id,note}),updateCancellation:(id,patch)=>execute("updateCancellation",{id,patch}),flagMessage:(jobId,messageId,note)=>execute("flagMessage",{jobId,messageId,note}),reviewCall:(jobId,callId,patch)=>execute("reviewCall",{jobId,callId,patch}),reviewInstapay:(id,reviewStatus,note)=>execute("reviewInstapay",{id,status:reviewStatus,note}),setWalletFrozen:(ownerId,frozen,reason)=>execute("setWalletFrozen",{ownerId,frozen,reason}),deleteJob:(id)=>execute("deleteJob",{id}),
    createComplaint:(input)=>execute("createComplaint",{input}),updateComplaint:(id,patch)=>execute("updateComplaint",{id,patch}),setCaseOwner:(id,adminId)=>execute("setCaseOwner",{id,adminId}),setCaseSeverity:(id,severity)=>execute("setCaseSeverity",{id,severity}),addCaseNote:(id,note)=>execute("addCaseNote",{id,note}),closeCase:(id)=>execute("closeCase",{id}),reopenCase:(id)=>execute("reopenCase",{id}),deleteComplaint:(id)=>execute("deleteComplaint",{id}),
    createPayout:(providerId,amount,method)=>execute("createPayout",{providerId,amount,method}),verifyPayout:(id,reference)=>execute("verifyPayout",{id,reference}),createTransaction:(input)=>execute("createTransaction",{input}),updateTransaction:(id,patch)=>execute("updateTransaction",{id,patch}),
    createAdmin:(input)=>adminRequest<AdminUser>({action:"create",input}),resendInvitation:(id)=>adminRequest({action:"resend",id}),revokeInvitation:(id)=>adminRequest({action:"revoke",id}),updateAdmin:(id,patch)=>adminRequest({action:"update",id,patch}),deleteAdmin:(id)=>adminRequest({action:"delete",id}),toggleAdmin:(id)=>adminRequest({action:"toggle",id}),syncAuthUsers:()=>adminRequest({action:"sync-auth-users"}),createRole:(input)=>adminRequest<Role>({action:"role-create",input}),updateRole:(id,patch)=>adminRequest({action:"role-update",id,input:patch}),deleteRole:(id)=>adminRequest({action:"role-delete",id}),
    createPromo:(input)=>execute("createPromo",{input}),updatePromo:(id,patch)=>execute("updatePromo",{id,patch}),deletePromo:(id)=>execute("deletePromo",{id}),createNotification:(input)=>execute("createNotification",{input}),reset:refresh,refresh,resetDemoData:()=>demoResetRequest(),
  }),[adminRequest,demoResetRequest,execute,operationsRequest,refresh]);
  return <AdminDataContext.Provider value={{db,actions,loading,mutationPending:mutationCount>0,error}}>{children}</AdminDataContext.Provider>;
}

export function useAdminData(){const value=useContext(AdminDataContext);if(!value)throw new Error("useAdminData must be used inside AdminDataProvider");return value}
