"use client";
import { useState } from "react";
import { Image as ImageIcon, MessageSquare, Plus, Send, Trash2 } from "lucide-react";
import { useAdminData } from "@/components/admin-data-provider";
import { ConfirmDialog, FormDialog, RowActions } from "@/components/functional-dialogs";
import type { Banner, Category, SupportConversation } from "@/lib/types";

export function ContentManagementPage({notify}:{notify:(message:string)=>void}){const{db,actions}=useAdminData();const[tab,setTab]=useState<"categories"|"banners">("categories");const[creating,setCreating]=useState(false);const[editingCategory,setEditingCategory]=useState<Category|null>(null);const[editingBanner,setEditingBanner]=useState<Banner|null>(null);const[deleting,setDeleting]=useState<{type:"category"|"banner";id:string}|null>(null);
  return <div className="space-y-5"><div className="flex gap-2"><button onClick={()=>setTab("categories")} className={tab==="categories"?"btn-primary":"btn-secondary"}>Categories ({db.categories.length})</button><button onClick={()=>setTab("banners")} className={tab==="banners"?"btn-primary":"btn-secondary"}>Banners ({db.banners.length})</button><button onClick={()=>setCreating(true)} className="btn-primary ml-auto"><Plus className="h-4 w-4"/>Create {tab==="categories"?"category":"banner"}</button></div>{tab==="categories"?<div className="panel overflow-hidden"><table className="w-full"><thead><tr className="table-head"><th>Category</th><th>Description</th><th>Services</th><th>Status</th><th/></tr></thead><tbody>{db.categories.map((category)=><tr key={category.id} className="table-row"><td className="font-medium">{category.name}</td><td>{category.description}</td><td>{db.services.filter((service)=>service.categoryId===category.id).length}</td><td>{category.enabled?"Enabled":"Disabled"}</td><td><RowActions actions={[{label:"Edit",onClick:()=>setEditingCategory(category)},{label:category.enabled?"Disable":"Enable",onClick:()=>actions.updateCategory(category.id,{enabled:!category.enabled})},{label:"Delete",danger:true,onClick:()=>setDeleting({type:"category",id:category.id})}]}/></td></tr>)}</tbody></table>{!db.categories.length&&<Empty text="No Firestore categories yet"/>}</div>:<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{db.banners.map((banner)=><article key={banner.id} className="panel overflow-hidden"><div className="aspect-[16/7] bg-cover bg-center" style={{backgroundImage:`url(${banner.imageUrl})`}}/><div className="p-4"><div className="flex items-start gap-3"><div className="flex-1"><h3 className="font-medium">{banner.title}</h3><p className="mt-1 text-xs text-zinc-500">{banner.subtitle}</p></div><span className={banner.enabled?"text-emerald-400":"text-zinc-500"}>{banner.enabled?"Active":"Disabled"}</span></div><div className="mt-4 flex gap-2"><button onClick={()=>setEditingBanner(banner)} className="btn-secondary">Edit</button><button onClick={()=>actions.updateBanner(banner.id,{enabled:!banner.enabled})} className="btn-secondary">{banner.enabled?"Disable":"Enable"}</button><button onClick={()=>setDeleting({type:"banner",id:banner.id})} className="icon-btn text-red-400"><Trash2 className="h-4 w-4"/></button></div></div></article>)}{!db.banners.length&&<div className="md:col-span-2 xl:col-span-3"><Empty text="No Firestore banners yet"/></div>}</div>}
  <FormDialog open={creating&&tab==="categories"} onClose={()=>setCreating(false)} title="Create category" fields={[{name:"name",label:"Name",required:true},{name:"description",label:"Description",type:"textarea",required:true}]} onSubmit={async(values)=>{await actions.createCategory({name:values.name,description:values.description});notify("Category saved to Firestore")}}/>
  <FormDialog open={!!editingCategory} onClose={()=>setEditingCategory(null)} title="Edit category" initial={editingCategory?{name:editingCategory.name,description:editingCategory.description}:{}} fields={[{name:"name",label:"Name",required:true},{name:"description",label:"Description",type:"textarea",required:true}]} onSubmit={(values)=>actions.updateCategory(editingCategory!.id,{name:values.name,description:values.description})}/>
  <FormDialog open={(creating&&tab==="banners")||!!editingBanner} onClose={()=>{setCreating(false);setEditingBanner(null)}} title={editingBanner?"Edit banner":"Create banner"} initial={editingBanner?{title:editingBanner.title,subtitle:editingBanner.subtitle,imageUrl:editingBanner.imageUrl,actionUrl:editingBanner.actionUrl??"",sortOrder:editingBanner.sortOrder}:{sortOrder:0}} fields={[{name:"title",label:"Title",required:true},{name:"subtitle",label:"Subtitle",required:true},{name:"imageUrl",label:"Firebase Storage or HTTPS image URL",required:true},{name:"actionUrl",label:"Action URL"},{name:"sortOrder",label:"Sort order",type:"number",required:true,min:0}]} onSubmit={(values)=>editingBanner?actions.updateBanner(editingBanner.id,{title:values.title,subtitle:values.subtitle,imageUrl:values.imageUrl,actionUrl:values.actionUrl,sortOrder:Number(values.sortOrder)}):actions.createBanner({title:values.title,subtitle:values.subtitle,imageUrl:values.imageUrl,actionUrl:values.actionUrl,sortOrder:Number(values.sortOrder),enabled:true})}/>
  <ConfirmDialog open={!!deleting} onClose={()=>setDeleting(null)} title={`Delete ${deleting?.type}?`} description="This removes the Firestore document immediately." onConfirm={()=>deleting?.type==="category"?actions.deleteCategory(deleting.id):deleting?actions.deleteBanner(deleting.id):undefined}/></div>}

export function SupportConversationsPage({notify}:{notify:(message:string)=>void}){const{db,actions}=useAdminData();const[create,setCreate]=useState(false);const[selected,setSelected]=useState<SupportConversation|null>(null);const[message,setMessage]=useState(false);const[deleting,setDeleting]=useState<SupportConversation|null>(null);const current=selected?db.conversations.find((item)=>item.id===selected.id)??selected:null;return <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><div className="panel overflow-hidden"><div className="flex items-center border-b border-white/[.07] p-4"><div><h2 className="font-semibold">Support conversations</h2><p className="text-xs text-zinc-500">Realtime Firestore threads</p></div><button onClick={()=>setCreate(true)} className="btn-primary ml-auto"><Plus className="h-4 w-4"/>New</button></div>{db.conversations.map((conversation)=><button key={conversation.id} onClick={()=>setSelected(conversation)} className="flex w-full items-center gap-3 border-b border-white/[.05] p-4 text-left hover:bg-white/[.03]"><MessageSquare className="h-4 w-4 text-indigo-400"/><span className="min-w-0 flex-1"><b className="block truncate text-xs">{conversation.subject}</b><small className="text-zinc-600">{conversation.priority} · {conversation.status} · {conversation.messages.length} messages</small></span></button>)}{!db.conversations.length&&<Empty text="No support conversations"/>}</div><div className="panel min-h-[520px]">{current?<><div className="flex items-center border-b border-white/[.07] p-4"><div className="flex-1"><h2 className="font-semibold">{current.subject}</h2><p className="text-xs text-zinc-500">{current.id} · {current.status}</p></div><button onClick={()=>actions.updateConversation(current.id,{status:current.status==="Closed"?"Open":"Closed"})} className="btn-secondary">{current.status==="Closed"?"Reopen":"Close"}</button><button onClick={()=>setDeleting(current)} className="icon-btn ml-2 text-red-400"><Trash2 className="h-4 w-4"/></button></div><div className="space-y-3 p-5">{current.messages.map((item)=><div key={item.id} className="rounded-2xl border border-white/[.07] p-4"><div className="text-xs font-medium">{item.senderName}<span className="ml-2 text-[9px] text-zinc-600">{item.senderType}</span></div><p className="mt-2 text-xs text-zinc-300">{item.text}</p><div className="mt-2 text-[9px] text-zinc-600">{new Date(item.sentAt).toLocaleString()}</div></div>)}<button onClick={()=>setMessage(true)} className="btn-primary"><Send className="h-4 w-4"/>Reply</button></div></>:<div className="grid h-full min-h-[520px] place-items-center text-sm text-zinc-600">Select a conversation</div>}</div>
  <FormDialog open={create} onClose={()=>setCreate(false)} title="Create support conversation" fields={[{name:"subject",label:"Subject",required:true},{name:"priority",label:"Priority",type:"select",required:true,options:["Low","Normal","High","Urgent"].map((value)=>({label:value,value}))},{name:"customerId",label:"Customer",type:"select",options:db.customers.map((item)=>({label:`${item.name} · ${item.phone}`,value:item.id}))},{name:"providerId",label:"Provider",type:"select",options:db.providers.map((item)=>({label:`${item.providerId} · ${item.name}`,value:item.id}))},{name:"jobId",label:"Order",type:"select",options:db.jobs.map((item)=>({label:`${item.id} · ${item.service}`,value:item.id}))}]} onSubmit={(values)=>actions.createConversation({subject:values.subject,priority:values.priority as SupportConversation["priority"],customerId:values.customerId||undefined,providerId:values.providerId||undefined,jobId:values.jobId||undefined})}/>
  <FormDialog open={message} onClose={()=>setMessage(false)} title="Reply to conversation" fields={[{name:"message",label:"Message",type:"textarea",required:true}]} onSubmit={async(values)=>{if(current){await actions.addConversationMessage(current.id,values.message);notify("Reply saved to Firestore")}}}/><ConfirmDialog open={!!deleting} onClose={()=>setDeleting(null)} title="Delete conversation?" description="This permanently removes the Firestore conversation." onConfirm={()=>deleting?actions.deleteConversation(deleting.id):undefined}/></div>}

function Empty({text}:{text:string}){return <div className="grid min-h-40 place-items-center p-6 text-xs text-zinc-600"><span className="flex items-center gap-2"><ImageIcon className="h-4 w-4"/>{text}</span></div>}
