// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the Technician app.
///
/// Points at the same live `task-app-20c5f` project as the Customer app — the
/// two clients share one Firestore, Auth, and Storage backend. The Android/iOS
/// app registrations here mirror the customer values for the dev/emulator loop;
/// re-run the FlutterFire CLI against the `com.task.technician` bundle before a
/// production release so App Check attestation resolves to this app.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjalTeSxDICm_vcUCpY9oj-TyfAGxyixQ',
    appId: '1:1071154220753:web:79460c9c8d79f12d5dfff0',
    messagingSenderId: '1071154220753',
    projectId: 'task-app-20c5f',
    authDomain: 'task-app-20c5f.firebaseapp.com',
    storageBucket: 'task-app-20c5f.firebasestorage.app',
    measurementId: 'G-CES23N88MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYeBkqiWJTiP-VPebzE3EWFt4MptMOqgA',
    appId: '1:1071154220753:android:e6210ad2f5e86f4c5dfff0',
    messagingSenderId: '1071154220753',
    projectId: 'task-app-20c5f',
    storageBucket: 'task-app-20c5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1xrFzaYnve_Z2EUNUxJM0xK1F7SBOI-s',
    appId: '1:1071154220753:ios:755c6f8b73d734d55dfff0',
    messagingSenderId: '1071154220753',
    projectId: 'task-app-20c5f',
    storageBucket: 'task-app-20c5f.firebasestorage.app',
    iosBundleId: 'com.task.technician',
  );
}
