import 'package:flutter/material.dart';
import 'package:task_domain/task_domain.dart';

/// Material icon for a job category. UI-only — the pure-Dart domain never holds
/// `IconData`, so this mapping is the single source of category iconography.
IconData categoryIcon(JobCategory category) => switch (category) {
      JobCategory.plumbing => Icons.plumbing_rounded,
      JobCategory.electrical => Icons.bolt_rounded,
      JobCategory.ac => Icons.ac_unit_rounded,
      JobCategory.cleaning => Icons.cleaning_services_rounded,
      JobCategory.carpentry => Icons.handyman_rounded,
      JobCategory.painting => Icons.format_paint_rounded,
      JobCategory.satelliteInstallation => Icons.satellite_alt_rounded,
      JobCategory.smartHome => Icons.home_max_rounded,
      JobCategory.tilesHandyman => Icons.grid_view_rounded,
      JobCategory.masonStones => Icons.foundation_rounded,
      JobCategory.plaster => Icons.imagesearch_roller_rounded,
      JobCategory.smith => Icons.hardware_rounded,
      JobCategory.parquet => Icons.view_module_rounded,
      JobCategory.gypsumWorks => Icons.architecture_rounded,
      JobCategory.gypsumBoard => Icons.dashboard_rounded,
      JobCategory.marbleGranite => Icons.countertops_rounded,
      JobCategory.alumetal => Icons.window_rounded,
      JobCategory.glassCecurit => Icons.blur_on_rounded,
      JobCategory.curtainsUpholstery => Icons.curtains_rounded,
      JobCategory.woodPainter => Icons.brush_rounded,
      JobCategory.movingServices => Icons.local_shipping_rounded,
      JobCategory.puCornices => Icons.crop_square_rounded,
      JobCategory.materialWinch => Icons.precision_manufacturing_rounded,
      JobCategory.appliancesMaintenance => Icons.kitchen_rounded,
      JobCategory.swimmingPool => Icons.pool_rounded,
      JobCategory.pestControl => Icons.pest_control_rounded,
    };

/// Accent tint used for a category tile glow.
Color categoryTint(JobCategory category) => switch (category) {
      JobCategory.plumbing => const Color(0xFF38BDF8),
      JobCategory.electrical => const Color(0xFFFBBF24),
      JobCategory.ac => const Color(0xFF22D3EE),
      JobCategory.cleaning => const Color(0xFF34D399),
      JobCategory.carpentry => const Color(0xFFF472B6),
      JobCategory.painting => const Color(0xFFA78BFA),
      JobCategory.satelliteInstallation => const Color(0xFF818CF8),
      JobCategory.smartHome => const Color(0xFF2DD4BF),
      JobCategory.tilesHandyman => const Color(0xFFE879F9),
      JobCategory.masonStones => const Color(0xFFF97316),
      JobCategory.plaster => const Color(0xFFFCA5A5),
      JobCategory.smith => const Color(0xFF94A3B8),
      JobCategory.parquet => const Color(0xFFD97706),
      JobCategory.gypsumWorks => const Color(0xFFC084FC),
      JobCategory.gypsumBoard => const Color(0xFF67E8F9),
      JobCategory.marbleGranite => const Color(0xFFFDE68A),
      JobCategory.alumetal => const Color(0xFF60A5FA),
      JobCategory.glassCecurit => const Color(0xFF5EEAD4),
      JobCategory.curtainsUpholstery => const Color(0xFFF9A8D4),
      JobCategory.woodPainter => const Color(0xFFBEF264),
      JobCategory.movingServices => const Color(0xFFFB923C),
      JobCategory.puCornices => const Color(0xFFD8B4FE),
      JobCategory.materialWinch => const Color(0xFFFDA4AF),
      JobCategory.appliancesMaintenance => const Color(0xFF6EE7B7),
      JobCategory.swimmingPool => const Color(0xFF7DD3FC),
      JobCategory.pestControl => const Color(0xFFFCA5A5),
    };
